"""HTML report generator for CyberShield scan results."""

from __future__ import annotations

import html
from datetime import datetime
from typing import TYPE_CHECKING

from cybershield.reports.base import BaseReport

if TYPE_CHECKING:
    from cybershield.core import ScanResult, Vulnerability


SEVERITY_COLORS = {
    "CRITICAL": "#dc2626",
    "HIGH": "#ea580c",
    "MEDIUM": "#ca8a04",
    "LOW": "#16a34a",
    "INFO": "#2563eb",
}


class HTMLReportGenerator(BaseReport):
    """Generates styled HTML security scan reports."""

    format_name = "html"
    file_extension = ".html"

    def _render(self, result: ScanResult) -> str:
        """Render an HTML report from scan results."""
        summary = result.summary
        vulns_html = self._render_vulnerabilities(
            result.sorted_vulnerabilities()
        )
        errors_html = self._render_errors(result.errors)

        return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CyberShield Scan Report — {html.escape(result.target_url)}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0f172a; color: #e2e8f0; line-height: 1.6;
    padding: 2rem; max-width: 1000px; margin: 0 auto;
  }}
  h1 {{ color: #38bdf8; margin-bottom: 0.5rem; }}
  h2 {{ color: #94a3b8; margin: 2rem 0 1rem; border-bottom: 1px solid #334155; padding-bottom: 0.5rem; }}
  .meta {{ color: #64748b; font-size: 0.9rem; margin-bottom: 2rem; }}
  .summary {{
    display: grid; grid-template-columns: repeat(5, 1fr); gap: 1rem;
    margin: 1.5rem 0;
  }}
  .summary-card {{
    background: #1e293b; border-radius: 8px; padding: 1rem; text-align: center;
    border: 1px solid #334155;
  }}
  .summary-card .count {{ font-size: 2rem; font-weight: bold; }}
  .summary-card .label {{ font-size: 0.85rem; color: #94a3b8; }}
  .vuln {{
    background: #1e293b; border-radius: 8px; padding: 1.5rem;
    margin-bottom: 1rem; border-left: 4px solid;
  }}
  .vuln .title {{ font-size: 1.1rem; font-weight: 600; margin-bottom: 0.5rem; }}
  .vuln .severity {{
    display: inline-block; padding: 2px 10px; border-radius: 4px;
    font-size: 0.8rem; font-weight: 600; color: #fff; margin-bottom: 0.5rem;
  }}
  .vuln .field {{ margin: 0.5rem 0; }}
  .vuln .field-label {{ color: #94a3b8; font-size: 0.85rem; }}
  .vuln pre {{
    background: #0f172a; padding: 0.75rem; border-radius: 4px;
    font-size: 0.85rem; overflow-x: auto; margin-top: 0.25rem;
  }}
  .ai-explanation {{
    background: #172554; border: 1px solid #1e40af; border-radius: 6px;
    padding: 1rem; margin-top: 0.75rem;
  }}
  .ai-explanation .label {{ color: #60a5fa; font-weight: 600; margin-bottom: 0.5rem; }}
  .errors {{ color: #fbbf24; }}
  footer {{ text-align: center; color: #475569; margin-top: 3rem; font-size: 0.85rem; }}
</style>
</head>
<body>
  <h1>🛡 CyberShield Scan Report</h1>
  <div class="meta">
    <strong>Target:</strong> {html.escape(result.target_url)}<br>
    <strong>Date:</strong> {datetime.fromtimestamp(result.start_time).strftime('%Y-%m-%d %H:%M:%S')}<br>
    <strong>Duration:</strong> {result.duration:.1f}s<br>
    <strong>Modules:</strong> {', '.join(result.modules_used)}
  </div>

  <h2>Summary</h2>
  <div class="summary">
    <div class="summary-card">
      <div class="count" style="color: {SEVERITY_COLORS['CRITICAL']}">{summary['CRITICAL']}</div>
      <div class="label">Critical</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: {SEVERITY_COLORS['HIGH']}">{summary['HIGH']}</div>
      <div class="label">High</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: {SEVERITY_COLORS['MEDIUM']}">{summary['MEDIUM']}</div>
      <div class="label">Medium</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: {SEVERITY_COLORS['LOW']}">{summary['LOW']}</div>
      <div class="label">Low</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: {SEVERITY_COLORS['INFO']}">{summary['INFO']}</div>
      <div class="label">Info</div>
    </div>
  </div>

  <h2>Findings ({len(result.vulnerabilities)})</h2>
  {vulns_html}

  {errors_html}

  <footer>
    Generated by CyberShield OSS v0.1.0 &mdash;
    <a href="https://github.com/minidu-lab/cybershield-oss" style="color: #38bdf8;">GitHub</a>
  </footer>
</body>
</html>"""

    def _render_vulnerabilities(
        self, vulnerabilities: list[Vulnerability]
    ) -> str:
        """Render vulnerability cards."""
        if not vulnerabilities:
            return '<p style="color: #22c55e;">No vulnerabilities found.</p>'

        cards = []
        for vuln in vulnerabilities:
            color = SEVERITY_COLORS.get(vuln.severity, "#64748b")
            ai_section = ""
            if vuln.ai_explanation:
                ai_section = f"""
    <div class="ai-explanation">
      <div class="label">🤖 AI Explanation (Claude)</div>
      <div>{html.escape(vuln.ai_explanation)}</div>
    </div>"""

            cards.append(f"""\
  <div class="vuln" style="border-left-color: {color};">
    <span class="severity" style="background: {color};">{vuln.severity}</span>
    {f'<span style="color: #64748b; font-size: 0.8rem; margin-left: 0.5rem;">{html.escape(vuln.cwe_id)}</span>' if vuln.cwe_id else ''}
    <div class="title">{html.escape(vuln.title)}</div>
    <div class="field">
      <span class="field-label">URL:</span> {html.escape(vuln.url)}
    </div>
    <div class="field">
      <span class="field-label">Description:</span> {html.escape(vuln.description)}
    </div>
    {f'<div class="field"><span class="field-label">Evidence:</span><pre>{html.escape(vuln.evidence)}</pre></div>' if vuln.evidence else ''}
    <div class="field">
      <span class="field-label">Remediation:</span>
      <pre>{html.escape(vuln.remediation)}</pre>
    </div>
    {ai_section}
  </div>""")

        return "\n".join(cards)

    def _render_errors(self, errors: list[str]) -> str:
        """Render error section if any errors occurred."""
        if not errors:
            return ""
        items = "\n".join(
            f"    <li>{html.escape(e)}</li>" for e in errors
        )
        return f"""
  <h2 class="errors">⚠ Errors</h2>
  <ul class="errors">
{items}
  </ul>"""
